version: '3'

services:
 project:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./project:/opt/project"]
   environment:
     PORT: 8080
     FLASK_DEBUG: "True"
   ports:
     - "8080:8080"
